version: '3.1'
services:

  redis:
    image: 'redis:7.0'
    networks:
      - hmpps
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  app:
    build: .
    networks:
      - hmpps
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - AUTHORISED_ROLES=ROLE_PRISONS_REPORTING_USER
      - HMPPS_AUTH_URL=https://sign-in-dev.hmpps.service.justice.gov.uk/auth
      - HMPPS_MANAGE_USERS_URL=https://manage-users-api-dev.hmpps.service.justice.gov.uk
      - REPORTING_API_URL=https://digital-prison-reporting-mi-dev.hmpps.service.justice.gov.uk
      - TOKEN_VERIFICATION_API_URL=https://token-verification-api-dev.prison.service.justice.gov.uk
      - TOKEN_VERIFICATION_ENABLED=true
      # These will need to match creds in the dev auth service
      - API_CLIENT_ID=stu-pegg
      - API_CLIENT_SECRET=SCeMoeD5XK9%-BDI3.5ERk.KoIj(lK:IT:Q$XHzPzQOxcQD,+xh.C5!(pxb&
      - SYSTEM_CLIENT_ID=stu-pegg
      - SYSTEM_CLIENT_SECRET=SCeMoeD5XK9%-BDI3.5ERk.KoIj(lK:IT:Q$XHzPzQOxcQD,+xh.C5!(pxb&

networks:
  hmpps:
