# Please see the "Deployment to Cloud Platform Environment" section of the README regarding updates to this file.
apiVersion: v1
kind: Secret
metadata:
  name: hmpps-auth
type: Opaque
data:
  api_client_id: cGxhY2Vob2xkZXI=
  api_client_secret: cGxhY2Vob2xkZXI=
  system_client_id: cGxhY2Vob2xkZXI=
  system_client_secret: cGxhY2Vob2xkZXI=
