# Per environment values which override defaults in hmpps-digital-prison-reporting-mi-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: digital-prison-reporting-mi-ui-test.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://digital-prison-reporting-mi-ui-test.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    REPORTING_API_URL: "http://hmpps-digital-prison-reporting-mi-test.hmpps-digital-prison-reporting-mi-test.svc.cluster.local"
    TOKEN_VERIFICATION_ENABLED: true
    AUTHORISED_ROLES: ROLE_PRISONS_REPORTING_USER

  allowlist:
    hmp-parc-1: 217.161.76.162/32
    hmp-parc-2: 217.161.76.154/32
    groups:
      - circleci
      - internal
      - prisons
      - private_prisons

generic-prometheus-alerts:
  alertSeverity: digital-prison-reporting-dev
