---
generic-service:
  nameOverride: hmpps-digital-prison-reporting-mi-ui

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-digital-prison-reporting-mi-ui
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-digital-prison-reporting-mi-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    TOKEN_VERIFICATION_ENABLED: "true"
    REDIS_TLS_ENABLED: "true"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-digital-prison-reporting-mi-ui-ec-cluster-output:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    ui-session-secret:
      SESSION_SECRET: "session_secret"
    hmpps-auth:
      API_CLIENT_ID: "api_client_id"
      API_CLIENT_SECRET: "api_client_secret"
      SYSTEM_CLIENT_ID: "system_client_id"
      SYSTEM_CLIENT_SECRET: "system_client_secret"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live-1: "35.178.209.113/32"
    cloudplatform-live-2: "3.8.51.207/32"
    cloudplatform-live-3: "35.177.252.54/32"
    health-check: "3.11.70.209/32"
    it-health-check: "54.37.241.156/32"

generic-prometheus-alerts:
  targetApplication: hmpps-digital-prison-reporting-mi-ui
